# Generated by Django 4.0.4 on 2022-05-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_source_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.source'),
            preserve_default=False,
        ),
    ]
