# Generated by Django 4.0.4 on 2022-05-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_message_created_message_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='source',
            old_name='author',
            new_name='user',
        ),
    ]
