# Generated by Django 4.0.4 on 2022-06-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_message_options_rename_author_source_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='source-content/'),
        ),
    ]
