# Generated by Django 4.0.4 on 2022-06-24 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_source_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='source-content/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['md'])]),
        ),
    ]
